[package]
name = "integrationtests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[test]]
name = "integrationtests"
path = "tests/tests.rs"

[lib]
name = "lnbitsmock"
path = "src/lnbitsmock.rs"

[dependencies]
rand = "0.8.5"
axum = "0.6.18"
anyhow = {version="1.0.71", features = ["backtrace"] }
serde = { version = "1.0.164", features = ["derive"] }
serde_derive = "1.0.160"
serde_json = "1.0.97"
lightning-invoice = "0.23.0"
lightning = "0.0.115"
tokio = { version = "1.28.2", features = ["full"] }
tower-http = { version = "0.4.1", features = ["trace", "cors"] }
hyper = { version = "0.14", features = ["full"] }
bitcoin_hashes = { version = "0.12.0", default-features = false }
secp256k1 = { version = "0.24.0", default-features = false, features = ["recovery", "alloc","rand"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"

[dev-dependencies]
anyhow = {version="1.0.71", features = ["backtrace"] }
tokio = { version = "1.28.2", features = ["full"] }
reqwest = {version= "0.11.18", default-features = false}
cashurs-mint = { path = "../mint"}
cashurs-wallet = { path = "../wallet"}
cashurs-core = { path = "../core"}
tempfile = "3.6.0"



