[package]
name = "moksha-mint"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[[bin]]
name = "moksha-mint"
path = "src/bin/moksha-mint.rs"


[lib]
name = "mokshamint"
path = "src/lib.rs"


[dependencies]
async-trait = "0.1.70"
bitcoin_hashes = "0.12.0"
anyhow = {version="1.0.71", features = ["backtrace"] }
axum = "0.6.18"
hyper = "0.14.27"
serde = { version = "1.0.164", features = ["derive"] }
serde_derive = "1.0.160"
serde_json = "1.0.99"
tokio = { version = "1.29.1", features = ["full"] }
tower-http = { version = "0.4.1", features = ["trace", "cors", "fs"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
secp256k1 = {version="0.27.0", features = [ "rand", "serde" ]}
thiserror = "1.0.40"
moksha-core = { path = "../moksha-core" }
rocksdb = "0.21.0"
lightning-invoice = "0.23.0"
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls-webpki-roots", "socks"] }
url = "2.4.0"
dotenvy = "0.15.7"

[dev-dependencies]
tempfile = "3.6.0"
tower = "0.4.13"
mockall = "0.11.4"
